version: '3.7'

services:
  vue-app:
    build: .
    container_name: pusb-client
    stdin_open: true
    tty: true
    volumes:
      - "/app/node_modules"
      - ".:/app"
    ports:
      - "3006:80"